# Creating a Price Index in the Middle East

#### Keywords

CPI, Middle East,

Unlike many western countries, whose governments have historically collected large quantities of data, the Middle East has a limited collection over a much shorter period.  While many basic economic statistics are collected by these countries, they may be considered suspect by external investors who would see most of the governments of the region as being biased about the presentation of these data.  As well, some of the data is not collected in a timely manner.

The consumer price index (CPI) and the inflation rate are often seen as critical information for investment decisions.  (CPI is a measure of price changes in household goods such as foods, services, and transport, and inflation is the annual percentage change in CPI.)  Given recent economic changes (low oil prices) these countries are now looking for new sources of revenue, which may require funding from external investors.  However, investors may feel suspicious of the national data and as a result not be comfortable investing, or if they do decide to invest, they could require higher returns to compensate for higher risk. 

To solve this, we will provide an independent collection and presentation of the price data,  that is produced on a monthly basis.  The first step will be to create price baskets of goods for the countries to be covered.  Like many countries around the world, Middle East countries are moving towards online shopping, and so the price of many goods is available on the internet.  We will implement a weekly scrape of the sites and begin a database of product prices.  Given the multi-cultural makeup of some these countries and the vast disparity between incomes classes, it will be prudent to create multiple baskets reflecting typical buying patterns within the groups.  While service prices are more complicated, things like tuition can be easily scraped from websites as well. 

Once completed, we will have an independent verification of the data presented by each nation, which can be compared alongside the official government statistics.  This independent data could help give investors peace of mind, as well as make adjustment to the perceived risk of investing in a country.  However, there will still be some uncertainty as some data that would typically be easily collected in other countries, for example, things like transport and healthcare, could not be gleaned from the internet. Moreover, to assure investors that the index is not a “black box”, we would be transparent in the data calculations, data set, and the assumptions used.  
