---
title: "W201 Portfolio"
author: "Oski Bear"
date: "MIDS Summer 2017"
site: bookdown::bookdown_site
documentclass: book
---

<!-- This won't be displayed but it will initialize your R session. Add any R libraries you need here. -->
```{r init,include=FALSE,echo=FALSE}
library(magrittr)
```


# Welcome!


### Abstract of my first cool idea

Investing in less developed countries and markets can provide investors with extra returns. But with the additional returns, comes additional risk. One problem with investing in frontier markets is that key macroeconomic data is not always readily available, timely and independent from government officials, making it difficult for investors, and others, to get a clear view of the economy.  We will create independent datasets, using publicly available online data. We focus on Middle East countries, where the population is relatively wealthy and online shopping is gaining more traction. Using published data from major grocery stores, online shopping sites and other services, we aim to create a key dataset, such as a consumer price index, which can be used to analyze inflation trends and business cycles.

### Abstract of my second cool idea

A sad fact to anyone suffering from a degenerative neurological disease, such as Parkinson’s Disease (PD) or ALS, is that they will lose their voice eventually. To lessen this impact of these diseases, our idea is to design a tool, building on current technology and using data science concepts that will improve the patient’s quality of life through voice simulation and enhancement.

## About the author

The author is a long in the tooth technology acolyte who has had many areas of specialty over a varied career.

*Updated: `r Sys.Date()`*
